rust-num/num-bigint

- Cargo.toml
- benches/gcd.rs
- src/algorithms.rs
- src/bigint.rs
- src/biguint.rs
- src/lib.rs
- src/tests/biguint.rs
This implements Stein's algorithm for bigints.
Asymptotically this has the same runtime complexity as the euclidean algorithm but it's faster because it avoids division in favor of bitshifts and subtractions.
There are faster algorithms for large bigints. For small ones, [gmp uses the binary gcd too](https://gmplib.org/manual/Binary-GCD.html).
I've run some benchmarks with the code in [this repo](https://github.com/Emerentius/bigint_gcd_bench)
This iterates through the sizes of 1-10 `BigDigit`s and generates 300 uniformly distributed random bigints at each size and computes the gcd for each combination with both Euclid's and Stein's algorithm. I'm only looking at combinations of numbers with the same number of `BigDigit`s
The speed gains are sizeable. See the benchmark results below. I'm …
> Implement Stein's algorithm for gcd

- README.md
The ApInt crate is a pure rust implementation for arbitrary fixed bitwidth modulo arithmetics of integers with a focus on correctness and efficiency - especially for smaller bit widths. It features a generic signless `ApInt` as well as signed counterparts `Int` (signed int) and `UInt` (unsigned int) that are thin wrappers around it. The implementation is unfinished in some parts but that should be fixed over time.
Link to crate at crates.io: https://crates.io/crates/apint
Link to repo at GitHub: https://github.com/robbepop/apint
> Add apint to README as another alternative

- src/bigint.rs
- src/biguint.rs
- src/macros.rs
- src/tests/bigint.rs
- src/tests/biguint.rs
This PR is relative to the [issue 4](https://github.com/rust-num/num-bigint/issues/4). This is a
very simple implementation, based on two macros. Maybe a more elegant
solution is possible for these, feel free to suggest.
Two tests for both `BigInt` and `BigUInt` have been added, one relative
to the `Sum`, the other to the `Product`.
> Implementation of std::iter::{Product, Sum}

- Cargo.toml
- src/bigint.rs
- src/biguint.rs
Won't work until a newer version of `num-traits` is pushed, but I figured I'd offer these now.
> Implement is_one for BigUint and BigInt.

- src/algorithms.rs
- src/biguint.rs
For `short_val + long_ref`, `long_ref + short_val` and `long_ref - short_val`, the current code extends the short value with zeros and then performs the operation. Instead, this commit splits the addition/subtraction into two parts, the lower and the higher parts. After performing the addition/subtraction on the low part, the short value is extended with the high part of the long reference, and the intermediate carry/borrow is then added to/subtracted from the high part.
> do not zero-extend for addition when val is shorter than ref

- src/bigint.rs
- src/biguint.rs
- src/macros.rs
- tests/bigint_bitwise.rs
This commit adds the following impls, giving results equivalent to what would be expected with two's complement.
* `impl Not for BigInt`
* `impl BitAnd<&BigInt> for BigInt`, `impl BitAndAssign<&BigInt> for BigInt`
* `impl BitOr<&BigInt> for BigInt`, `impl BitOrAssign<&BigInt> for BigInt`
* `impl BitXor<&BigInt> for BigInt`, `impl BitXorAssign<&BigInt> for BigInt`
I also added some tests. There is most probably some room for optimization, but the bitwise operations all operate in place using a single pass.
I did not add other implementations such as `impl BitAnd<BigInt> for BigInt`, those can be done later.
Edit: Fixes #13
> two's-complement logic operations on BigInt

- benches/bigint.rs
- src/bigrand.rs
- tests/rand.rs
Changes `gen_biguint` from a `push(gen::<u32>)` method to rand's [`fill_bytes`](https://docs.rs/rand/0.5.0/rand/trait.RngCore.html#tymethod.fill_bytes). This should improve performance in most cases.
- For small PRNGs which only natively generate 64 bits (like Xorshift64 or [`splitmix64.c`](http://prng.di.unimi.it/splitmix64.c)), this will no longer throw away half the bits generated. 
- For block PRNGs like `StdRng`, this should reduce overhead.
- For an SIMD PRNG (https://github.com/rust-lang-nursery/rand/issues/377), this would be a significant improvement.
```diff,ignore
name         no_fill ns/iter  fill ns/iter  diff ns/iter   diff %  speedup 
+rand_1009    256              222                    -34  -13.28%   x 1.15 
+rand_131072  27,366           14,715             -12,651 …
```
> switch gen_biguint to fill_bytes

- Cargo.toml
- benches/bigint.rs
- src/bigint.rs
- src/biguint.rs
- tests/roots.rs
Supersedes #51 .
Since there is now a `Roots` trait with `sqrt`, `cbrt` and `nth_root` methods in the `num-integer` crate, this PR implements it for `BigInt` and `BigUint` types. I also added inherent methods on both types to allow the users access to all these functions without having to import `Roots`.
PS: `nth_root` currently  uses `num_traits::pow`. Should we perhaps wait for #54 to get merged, and then replace the call to use the new `pow::Pow` implementation on `BigUint`?
> Implement Roots for BigInt and BigUint

- benches/bigint.rs
- src/bigint.rs
- src/biguint.rs
- tests/bigint.rs
- tests/biguint.rs
- tests/roots.rs
> Implement Pow for BigUint and BigInt

- src/bigint.rs
- src/biguint.rs
- tests/consts/mod.rs
- tests/macros/mod.rs
- Depends on #63 
- This is the second part to #40
> Implement operators with 128bits

- README.md
The apint crate is stable as of Rust version 1.26.
> Update README.md alternatives section for apint

- src/bigint.rs
- src/biguint.rs
- tests/bigint.rs
The trick for saving a byte on `0x800000..` only works for negative numbers. This caused +128 to be serialized as `0x80` which is -128. So pretty bad bug.
> Fix `to_signed_bytes_*` for positive number with leading `0x80`

- README.md
Rug 1.4.0 now requires rust 1.31.
> update min rustc for the rug crate

- src/bigint.rs
Adds documentation explaining why `ToBigInt` can return `None` in some cases, and when it can be ignored.
> Document ToBigInt behaviour

- src/algorithms.rs
- src/bigint.rs
- src/biguint.rs
- src/lib.rs
- src/macros.rs
- src/monty.rs
Resolves #66
As suggested in the issue, I used `cargo clippy` to find instances of casting using `as`. Running clippy reports a ton of warnings and some errors, so I used the following command to allow `clippy::all` but warn on `clippy::cast_lossless`, and output to file:
```
cargo clippy -- -A clippy::all -W clippy::cast_lossless > /path/to/output.txt 2>&1
```
There were two cases reported by clippy which I did **not** handle. The first case is casting that involves macro invocation and the warning looks like the following:
```
warning: casting u8 to u32 may become silently lossy if types change
--> src/macros.rs:220:41
|
220 |                       $imp::$method(self, other as $promo)
|  _________________________________________^
221 | |                 }
222 | |             }
223 | | …
```
> Use from() for lossless numerical type conversion

- src/biguint.rs
~This work is based on #77~
~This version only allow to take `&BigUint` as `exp` argument and doesn't manipulate `exp` not to copy the data of `exp`.~
> Optimize BigUint::modpow for even

- benches/bigint.rs
- src/algorithms.rs
- src/biguint.rs
Previously all calls to div/rem were using `algorithms::div_rem(u: &BigUint, d: &BigUint) -> (BigUint, BigUint)`. I renamed this method to `div_rem_ref` and added `algorithms::div_rem(u: BigUint, d: BigUint) -> (BigUint, BigUint)`. I also used this new method in `biguint.rs` when applicable. This reduces the amount of allocations needed.
> Add by value div_rem

- src/bigint.rs
- src/biguint.rs
Signed-off-by: Michael Lodder <redmike7@gmail.com>
> Added Pow for Big types

- Cargo.toml
- ci/test_full.sh
- src/bigint.rs
- src/biguint.rs
- src/lib.rs
- tests/quickcheck.rs
Aims to fix #5. Still needs plenty of work, like supporting signed `BigInts`
> add quickcheck arbitrary and some quickcheck tests

- src/bigint.rs
- src/biguint.rs
- tests/bigint.rs
- tests/biguint.rs
Fixes #103 
Added a simple check to the BigInt::lcm() in the case that both arguments are
zero. If this is the case, the method returns BigInt::zero().
Added test case to test/bigint.rs checking that lcm(0, 0) returns 0.
> Fix lcm (0,0) panic

- README.md
- src/bigrand.rs
- src/lib.rs
When using this crate I had trouble figuring out why I couldn't use the `RandomBits` structure. Hopefully future users will be less confused!
Doc locations:
* README
* `RandomBits` struct
* `RandBigInt` trait
> Document the "rand" feature.

- src/bigint.rs
- src/biguint.rs
This add access to the u32 internal representation but because it returns a Vec of u32, doesn't force you to commit to this internal representation.
> Add to_u32_digits to both BigInt and BigUint

- src/biguint.rs
- tests/modpow.rs
Unfortunately, there was cases modulus never happened
> Fix modpow for exp=1

- src/bigint.rs
- src/biguint.rs
* Use "least significant digit first" instead of "little endian" for    32-bit digits.
* Document ordering of BigInt::from_slice and    BigInt::assign_from_slice.
* Put a dash in "two's-complement" when used as an adjective.
* Change "u32" to "`u32`".
Fixes #124.
> Doc: some minor clarifications and formatting nits

- .travis.yml
- Cargo.toml
- README.md
- benches/bigint.rs
- benches/gcd.rs
- benches/roots.rs
- build.rs
- ci/big_quickcheck/Cargo.toml
- ci/big_quickcheck/src/lib.rs
- ci/big_rand/Cargo.toml
- ci/big_rand/src/lib.rs
- ci/big_rand/src/torture.rs
- ci/rustup.sh
- ci/test_full.sh
- src/bigint.rs
- src/bigrand.rs
- src/biguint.rs
- src/lib.rs
- tests/bigint.rs
- tests/biguint.rs
- tests/macros/mod.rs
- tests/rand.rs
- tests/roots.rs
- tests/torture.rs
This bumps rand and quickcheck to the latest version. We're about to ship num-bigint with this patch applied.
> Bump dependencies

- src/macros.rs
- tests/bigint_scalar.rs
- tests/biguint_scalar.rs
- tests/macros/mod.rs
> Fix promotion of negative isize

- .travis.yml
- build.rs
- src/bigint.rs
- src/biguint.rs
- src/lib.rs
Closes #120 
Currently contains:
*  `TryFrom` translations of existing conversion traits.
* A minimal Error type used for all `TryFrom` implementations.
Additional implemetations (e.g. `TryFrom<BigInt> for BigUint` which skips `clone()`) could be beneficial. Also, no new tests have been added since all new impls are basically thin adapters around existing, tested methods. It may be beneficial to add them regardless.
> Add TryFrom impls

- src/algorithms.rs
- src/bigint.rs
- src/biguint.rs
This brings it more in line with std's numbers, and lets the user actually know why it panicked.
> Add divide-by-zero panic messages

- src/bigint.rs
This was motivated by the new nightly `unsigned_abs()` inherent method on primitives, which is currently raising a future-compatibility warning that it will take precedence in the future. That would actually be fine, since they do the same thing, but the warning is annoying in the meantime.
So ours is now `uabs()`, and I also added a new `checked_uabs()` that cleans up the branching a bit.
> Rewrite the internal `unsigned_abs`

- src/biguint.rs
If a number gets below 1/4 of capacity, shrink_to_fit. Since Vec grows by 2, this amortizes well
for any sequence of sizes.
> Shrink overallocated capacity if a number gets a lot smaller.

- src/algorithms.rs
- src/lib.rs
- tests/biguint.rs
Avoid computing a multiple of the divisor (and thus allocating memory) in the division loop.
Instead, directly subtract a multiple of the divisor from the dividend.
Also compute a more accurate guess for the next digit of the result. The guess is now exact in
almost all cases. In those cases where it's not exact, it will be off by exactly 1.
> Improve performance of the basic division algorithm.

- build.rs
- src/algorithms.rs
When compiling for x86_64, with "u64_digit" enabled, some benchmarks are improved by using `_addcarry_u64` instead of the custom-written `adc` function, and using `_subborrow_u64)` instead of the custom-written `sbb` function.
The fib and fib2 benchmarks improved the most, most benchmarks improved a little, and a few were worse within the margin of error.
The only benchmark that did legitimately worse was the `gcd_euclid` family, but there's a comment after those benchmarks saying `// Integer for BigUint now uses Stein for gcd`. the stein benchmarks showed improvements with this change.
Looking at the generated assembly, it was generating adcq instructions both before and after the change, but post-change the code using adc is a little shorter. It's possible that the intrinsic provided …
> Use the _addcarry and _subborrow intrinsics when available

- src/biguint.rs
- tests/biguint.rs
Added `BigUint::count_ones()`, `BigUint::trailing_ones()`. Also minimal tests for these and `BigUint::trailing_zeros()`.
Closes Issue #174
> added BigUint::count_ones(), trailing_ones()

- src/algorithms.rs
- src/bigint.rs
- src/biguint.rs
- src/monty.rs
* There were a bunch of code quality Clippy warnings that didn't apply for various reasons.
* There was an ok_or() that could have been an ok_or_else() that Clippy caught. Turns out it's for a ZST, so doesn't matter, but was "fixed" anyway to silence Clippy.
This will hopefully make "cargo clippy" more useful for the next person.
> silenced a bunch of misleading Clippy warnings

- ci/big_quickcheck/Cargo.toml
- src/bigint.rs
- src/biguint.rs
- tests/bigint.rs
- tests/biguint.rs
This PR implements `bit` and `set_bit` for `BigUint` and `BigInt`.
The method names have been chosen to match those of Ramp (https://docs.rs/ramp/0.5.9/ramp/int/struct.Int.html#method.bit).
For `BigInt` the implementation uses the number's two's complement representation when the number is negative. This matches what libraries like Ramp or languages like Python do.
Resolves #172
> Get/set n-th bit of `BigUint` and `BigInt`

- src/bigint/convert.rs
- src/biguint/convert.rs
`From<bool> for {numeric}` has been around in `std` since 1.28, so it would make sense to have it for `BigInt` and `BigUint` too.
> Add From<bool> for BigInt and BigUint

- build.rs
This PR adds detection for 128-bit targets and cleans up the code a bit.
#263
> Use `u64_digit` for 128-bit targets

- README.md
`rust-gmp`, `ramp`, and `apint` are all unmaintained so I removed them. I added a column for fundamental features the crates have and added some new rows.
> Update alternatives list

- src/bigint.rs
- src/bigint/addition.rs
- src/bigint/bits.rs
- src/bigint/division.rs
- src/bigint/multiplication.rs
- src/bigint/power.rs
- src/bigint/shift.rs
- src/bigint/subtraction.rs
- src/biguint/addition.rs
- src/biguint/bits.rs
- src/biguint/division.rs
- src/biguint/multiplication.rs
- src/biguint/power.rs
- src/biguint/shift.rs
- src/biguint/subtraction.rs
- src/macros.rs
Out of 110 lifetime generics in 20 files, only 23 in 4 files were necessary for compilation. This should make code more readable and not affect behavior in any way.
Hopefully this works. I tested it locally on both 1.31 and the latest version 1.59.
> Removed unnecessary lifetime annotations

- src/lib.rs
The line moves f2 into f1 using `replace` but that can be done with assignment
(I'm a beginner to rust so it's very likely I've missed something)
> [docs] Use assignment instead of replace

- src/biguint/convert.rs
This might be better suited behind a new feature gate? We're trying to use `num-bigint` in a WASM project that's running on [CosmWasm](https://docs.cosmwasm.com/docs/0.16/). The code compiles fine, but when trying to execute the program it's rejected by the VM because it refuses to run bytecode containing floating point operations.
Turns out the codebase already does a good job of avoiding such operations with the `std` feature disabled, but it's still being used in `from_radix_digits_be`/`_le` to estimate the final result size. I've switched this out on the no std code path and it seems to run fine with this change.
> Refactor conversion methods to avoid floating points on `no_std`

- ci/test_full.sh
- src/bigint/division.rs
- src/biguint/division.rs
- tests/bigint.rs
- tests/biguint.rs
Now that a common trait for this has been sorted out (https://github.com/rust-num/num-traits/issues/159 implemented and merged in https://github.com/rust-num/num-traits/pull/195), we can now close https://github.com/rust-num/num-bigint/issues/146 by implementing the trait for `BigInt`s. This commit does just that.
> Implement Euclid division and remainder

- ci/big_quickcheck/src/lib.rs
- src/biguint/convert.rs
- tests/bigint.rs
- tests/biguint.rs
This makes the rounding consistent with primitive types, which, per IEEE-754, uses nearest-ties-to-even rounding.
See: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a6ab9b18a4982f881cd594061f096f8c
```rust
#[test]
fn test() {
use num::{BigInt, ToPrimitive};
let a: i128 = (1 << 120) + (1 << (120 - 53));
let b: i128 = 1 << (120 - 60);
assert_ne!(a as f64, (a + 1) as f64);
assert_eq!((a + b) as f64, (a + 1) as f64);
assert_eq!(BigInt::from(a).to_f64().unwrap(), a as f64);
// This works because the b is among the high 64 bits
assert_eq!(BigInt::from(a + b).to_f64().unwrap(), (a + b) as f64);
// This fails because 1 is just thrown away
assert_eq!(BigInt::from(a + 1).to_f64().unwrap(), (a + 1) as f64);
}
```
> Implement ties-to-even for Big[U]Int::to_{f32,f64}

- src/bigint/convert.rs
- src/biguint.rs
- src/biguint/convert.rs
- src/biguint/monty.rs
- src/biguint/power.rs
- src/biguint/shift.rs
- src/lib.rs
- tests/bigint.rs
- tests/modpow.rs
This fixes (or suppresses) all clippy warnings in the lib target. (It doesn't help for the test target.)
> Clippy fixes

- .github/workflows/ci.yaml
- .github/workflows/master.yaml
- .github/workflows/pr.yaml
- Cargo.toml
- README.md
- build.rs
- ci/rustup.sh
- ci/test_full.sh
- src/bigint/convert.rs
- src/biguint.rs
- src/biguint/convert.rs
- src/lib.rs
Earlier versions won't see the incompatible updates at all!
> Use namespaced-features to safely bump to MSRV 1.60

- benches/bigint.rs
- src/biguint/multiplication.rs
Hi maintainers of rust-num/num-bigint,
I've been hacking on PostgreSQL's numeric.c lately, implementing the Karatsuba algorithm [1].
During this work, I realised that when splitting by half the larger factor's size, then if the smaller factor is less than that, its high part will be zero. I realised that a variable that is zero usually means a formula can be simplified, so I tried to plug in the zero high1 in the formula, and voila, that eliminated a multiplication and most of the additions/subtractions, needing only one multiplication and an addition. This simplification felt too obvious to be novel, have looked around a bit but haven't found it so far. Should be mentioned on the Karatsuba Wikipedia or something I think.
I of course checked also Rust's implementation, and it also seems …
> Optimise multiplication

- src/biguint/multiplication.rs
This concerns only the comments for big integer multiplication where the formulas for the coefficients w0..w4 are explicitly listed. These were not completely correct. Please compare the formulas with https://en.wikipedia.org/wiki/Toom%E2%80%93Cook_multiplication#Interpolation.
> Fixed incorrect formulas for coefficients.

- src/bigint/convert.rs
- src/biguint/convert.rs
`strip_prefix` is stable [since 1.45.0](https://doc.rust-lang.org/nightly/std/primitive.str.html#method.strip_prefix), which is less than the MSRV (1.60) of this crate, and it generally [generates better code](https://rust.godbolt.org/z/nfcsv4Eb8).
> style: use strip_prefix instead of manual starts_with/slice
